extraction:
  cpp:
    prepare:
      packages:
        - libax25-dev
        - libconfig++-dev
        - libjansson-dev
        - libmicrohttpd-dev
        - libmosquitto-dev
        - libmysqlcppconn-dev
        - libwebsockets-dev
    configure:
      command:
        - mkdir _lgtm_build_dir
        - cd _lgtm_build_dir
        - cmake ..
    index:
      build_command:
        - cd _lgtm_build_dir
        - make
